import type { Metadata } from "next";

import { Montserrat } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "./layoutWrapper";

const montserratFont = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Camara municipal de Rerutaba",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={montserratFont.className}>
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
